### ISSUE TITLE
 Request for Spark! Tech Resources for editorai

### ISSUE THREAD

**Issue by JslYoon** [BU-Spark/se-editor-ai#5]
Junsun Yoon (lyoon02@bu.edu)
Benjamin Gardiner (bengard@bu.edu)
Mary Ann Nguyen (nhnguyen@bu.edu)
Tia Hannah (thannah@bu.edu)

Google Firebase - frontend web hosting, data store
Google Cloud Platform - backend (api) hosting

**Comment by IanSaucy** [comment]
Hey, what do you need GCP for? What do you plan to host there?

**Comment by JslYoon** [comment]
We will be hosting our backend (Flask) on GCP

**Comment by IanSaucy** [comment]
Okay, two things. 

I would highly encourage you to use FastAPI instead. 

2. We can get you setup with a project on railway for hosting the API. It is our preference for deployments(it's also easier to work with)

**Comment by JslYoon** [comment]
Ok that would be nice, we only said GCP because that was listed on the website https://buspark.io/documentation/compute-resources/request-resources
we can use railway

**Comment by langdon** [comment]
Ok, I am now confused. When we talked in the meeting the request was for user auth and document storage. You were considering mongodb for this and I suggested firebase as an alternative.

**Comment by IanSaucy** [comment]
Whatever is happening, @mannyakosah can you handle this ticket? Probably hold until what stuff is needed is fleshed. 

IF a backend is needed I would do FastAPI on Railway. But if one can get away with serverless functions then pure firebase would be good. Firebase supports both Python and JS/TS for functions now.

**Comment by JslYoon** [comment]
Yes, we need Firebase for frontend deployment & data storage. 
@langdon suggested that we would need smth to deploy the backend, so I put GCP as written on the website. But if you say FastAPI on Railway is better, we can do that instead.

**Comment by langdon** [comment]
OK, i think we are having some challenges on "naming". 

Web Pages: What do you plan to use for this? a static site generator (a la Jekyll) or something like react.js/next.js?
API Server: FastAPI on Railway sounds like the right answer
User Auth: Google Firebase
Document Storage: Google Firebase
Other Data Storage: ?? Do you need more data than user auth and document storage (I am thinking "no" but not sure)
Anything I missed: ??

The problem is "backend" and "frontend" do not have clear definitions anymore. I would consider your usage of Firebase "backend" and the API server as "backend" or "middleware." Web is usually "frontend" but user auth is kind of a mix of both.

**Comment by JslYoon** [comment]
Ok, so to recap:

Our structure will go as next.js - Flask - Firebase

We need Firebase to host our next.js app and deal with data store & user auth.

The reason I mentioned GCP was because we wanted to host Flask (API server) as it was the recommended stack on the spark website.
However, if FastAPI on Railway is better, we can use that to host our Flask server instead.

I think there was a misunderstanding, thank you!
